package modelo;
// Generated 07/09/2016 06:08:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Concepto generated by hbm2java
 */
public class Concepto  implements java.io.Serializable {


     private int idConcepto;
     private String nombre;
     private Set otrosgastoses = new HashSet(0);

    public Concepto() {
    }

	
    public Concepto(int idConcepto) {
        this.idConcepto = idConcepto;
    }
    public Concepto(int idConcepto, String nombre, Set otrosgastoses) {
       this.idConcepto = idConcepto;
       this.nombre = nombre;
       this.otrosgastoses = otrosgastoses;
    }
   
    public int getIdConcepto() {
        return this.idConcepto;
    }
    
    public void setIdConcepto(int idConcepto) {
        this.idConcepto = idConcepto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getOtrosgastoses() {
        return this.otrosgastoses;
    }
    
    public void setOtrosgastoses(Set otrosgastoses) {
        this.otrosgastoses = otrosgastoses;
    }




}


