package modelo;
// Generated 07/09/2016 06:08:04 PM by Hibernate Tools 4.3.1



/**
 * Cotizaciones generated by hbm2java
 */
public class Cotizaciones  implements java.io.Serializable {


     private String periodo;
     private Integer cotizacion;

    public Cotizaciones() {
    }

	
    public Cotizaciones(String periodo) {
        this.periodo = periodo;
    }
    public Cotizaciones(String periodo, Integer cotizacion) {
       this.periodo = periodo;
       this.cotizacion = cotizacion;
    }
   
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Integer getCotizacion() {
        return this.cotizacion;
    }
    
    public void setCotizacion(Integer cotizacion) {
        this.cotizacion = cotizacion;
    }




}


