package modelo;
// Generated 07/09/2016 06:08:04 PM by Hibernate Tools 4.3.1



/**
 * Cotizaciones generated by hbm2java
 */
public class Cotizaciones  implements java.io.Serializable {


     private String periodo;
     private Integer cotizacion;
     private Integer periodoInt;

    public Cotizaciones() {
    }

	
    public Cotizaciones(String periodo) {
        this.periodo = periodo;
    }
    public Cotizaciones(String periodo, Integer cotizacion, Integer periodoInt) {
       this.periodo = periodo;
       this.cotizacion = cotizacion;
       this.periodoInt=periodoInt;
    }
   
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Integer getCotizacion() {
        return this.cotizacion;
    }
    
    public void setCotizacion(Integer cotizacion) {
        this.cotizacion = cotizacion;
    }
    
    public int getPeriodoInt() {
        return this.periodoInt;
    }
    
    public void setPeriodoInt(int periodoInt) {
        this.periodoInt = periodoInt;
    }

    @Override
    public String toString() {
        return "Cotizaciones{" + "periodo: " + periodo + ", cotizacion: " + cotizacion + '}';
    }


    

}


