package modelo;
// Generated 30/08/2016 05:05:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Gastoscomunes generated by hbm2java
 */
public class Gastoscomunes  implements java.io.Serializable {


     private int idGastosComunes;
     private Monto monto;
     private Unidad unidad;
     private Integer monto_1;
     private Boolean bonificacion;
     private Integer estado;
     private Date fechaPago;
     private String periodo;
     private Integer periodoInt;

    public Gastoscomunes() {
    }

	
    public Gastoscomunes(int idGastosComunes, Monto monto, Unidad unidad) {
        this.idGastosComunes = idGastosComunes;
        this.monto = monto;
        this.unidad = unidad;
    }
    public Gastoscomunes(int idGastosComunes, Monto monto, Unidad unidad, Integer monto_1, Boolean bonificacion, Integer estado, Date fechaPago, String periodo, Integer periodoInt) {
       this.idGastosComunes = idGastosComunes;
       this.monto = monto;
       this.unidad = unidad;
       this.monto_1 = monto_1;
       this.bonificacion = bonificacion;
       this.estado = estado;
       this.fechaPago = fechaPago;
       this.periodo = periodo;
       this.periodoInt=periodoInt;
    }
   
    public int getIdGastosComunes() {
        return this.idGastosComunes;
    }
    
    public void setIdGastosComunes(int idGastosComunes) {
        this.idGastosComunes = idGastosComunes;
    }
    public Monto getMonto() {
        return this.monto;
    }
    
    public void setMonto(Monto monto) {
        this.monto = monto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Integer getMonto_1() {
        return this.monto_1;
    }
    
    public void setMonto_1(Integer monto_1) {
        this.monto_1 = monto_1;
    }
    public Boolean getBonificacion() {
        return this.bonificacion;
    }
    
    public void setBonificacion(Boolean bonificacion) {
        this.bonificacion = bonificacion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    
    public int getPeriodoInt() {
        return this.periodoInt;
    }
    
    public void setPeriodoInt(int periodoInt) {
        this.periodoInt = periodoInt;
    }
}