package modelo;
// Generated 07/09/2016 06:08:04 PM by Hibernate Tools 4.3.1



/**
 * Notacredito generated by hbm2java
 */
public class Notacredito  implements java.io.Serializable {


     private int idNotaCredito;
     private Monto monto;
     private Unidad unidad;
     private Integer monto_1;
     private String descripcion;

    public Notacredito() {
    }

	
    public Notacredito(int idNotaCredito, Monto monto, Unidad unidad) {
        this.idNotaCredito = idNotaCredito;
        this.monto = monto;
        this.unidad = unidad;
    }
    public Notacredito(int idNotaCredito, Monto monto, Unidad unidad, Integer monto_1, String descripcion) {
       this.idNotaCredito = idNotaCredito;
       this.monto = monto;
       this.unidad = unidad;
       this.monto_1 = monto_1;
       this.descripcion = descripcion;
    }
   
    public int getIdNotaCredito() {
        return this.idNotaCredito;
    }
    
    public void setIdNotaCredito(int idNotaCredito) {
        this.idNotaCredito = idNotaCredito;
    }
    public Monto getMonto() {
        return this.monto;
    }
    
    public void setMonto(Monto monto) {
        this.monto = monto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Integer getMonto_1() {
        return this.monto_1;
    }
    
    public void setMonto_1(Integer monto_1) {
        this.monto_1 = monto_1;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


