package modelo;
// Generated 07/09/2016 06:08:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Otrosgastos generated by hbm2java
 */
public class Otrosgastos  implements java.io.Serializable {


     private int idOtrosGastos;
     private Concepto concepto;
     private Monto monto;
     private Unidad unidad;
     private Integer secuencia;
     private String descripcion;
     private Integer monto_1;
     private Date fecha;
     private Boolean pago;

    public Otrosgastos() {
    }

	
    public Otrosgastos(int idOtrosGastos, Concepto concepto, Monto monto, Unidad unidad) {
        this.idOtrosGastos = idOtrosGastos;
        this.concepto = concepto;
        this.monto = monto;
        this.unidad = unidad;
    }
    public Otrosgastos(int idOtrosGastos, Concepto concepto, Monto monto, Unidad unidad, Integer secuencia, String descripcion, Integer monto_1, Date fecha, Boolean pago) {
       this.idOtrosGastos = idOtrosGastos;
       this.concepto = concepto;
       this.monto = monto;
       this.unidad = unidad;
       this.secuencia = secuencia;
       this.descripcion = descripcion;
       this.monto_1 = monto_1;
       this.fecha = fecha;
       this.pago = pago;
    }
   
    public int getIdOtrosGastos() {
        return this.idOtrosGastos;
    }
    
    public void setIdOtrosGastos(int idOtrosGastos) {
        this.idOtrosGastos = idOtrosGastos;
    }
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }
    public Monto getMonto() {
        return this.monto;
    }
    
    public void setMonto(Monto monto) {
        this.monto = monto;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Integer getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(Integer secuencia) {
        this.secuencia = secuencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getMonto_1() {
        return this.monto_1;
    }
    
    public void setMonto_1(Integer monto_1) {
        this.monto_1 = monto_1;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getPago() {
        return this.pago;
    }
    
    public void setPago(Boolean pago) {
        this.pago = pago;
    }




}


