package modelo;
// Generated 30/08/2016 05:05:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private int idTipoUsuario;
     private String nombre;
     private Set usuarios = new HashSet(0);

    public Tipousuario() {
    }

	
    public Tipousuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public Tipousuario(int idTipoUsuario, String nombre, Set usuarios) {
       this.idTipoUsuario = idTipoUsuario;
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
   
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


