package modelo;
// Generated 30/08/2016 05:05:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipobonificacion generated by hbm2java
 */
public class Tipobonificacion  implements java.io.Serializable {


     private int idTipoBonificacion;
     private Boolean tipoBonificacion;
     private Integer monto;
     private Set convenios = new HashSet(0);

    public Tipobonificacion() {
    }

	
    public Tipobonificacion(int idTipoBonificacion) {
        this.idTipoBonificacion = idTipoBonificacion;
    }
    public Tipobonificacion(int idTipoBonificacion, Boolean tipoBonificacion, Integer monto, Set convenios) {
       this.idTipoBonificacion = idTipoBonificacion;
       this.tipoBonificacion = tipoBonificacion;
       this.monto = monto;
       this.convenios = convenios;
    }
   
    public int getIdTipoBonificacion() {
        return this.idTipoBonificacion;
    }
    
    public void setIdTipoBonificacion(int idTipoBonificacion) {
        this.idTipoBonificacion = idTipoBonificacion;
    }
    public Boolean getTipoBonificacion() {
        return this.tipoBonificacion;
    }
    
    public void setTipoBonificacion(Boolean tipoBonificacion) {
        this.tipoBonificacion = tipoBonificacion;
    }
    public Integer getMonto() {
        return this.monto;
    }
    
    public void setMonto(Integer monto) {
        this.monto = monto;
    }
    public Set getConvenios() {
        return this.convenios;
    }
    
    public void setConvenios(Set convenios) {
        this.convenios = convenios;
    }




}


