package modelo;
// Generated 30/08/2016 05:05:39 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Tipousuario tipousuario;
     private String nombreUsuario;
     private String password;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Tipousuario tipousuario) {
        this.idUsuario = idUsuario;
        this.tipousuario = tipousuario;
    }
    public Usuario(int idUsuario, Tipousuario tipousuario, String nombreUsuario, String password) {
       this.idUsuario = idUsuario;
       this.tipousuario = tipousuario;
       this.nombreUsuario = nombreUsuario;
       this.password = password;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


